### ISSUE TITLE
请问下后台返回的接口参数有哪些，能提供一下么

### ISSUE THREAD

**Issue by zenghuabin** [unliar/oss-element-upload#2]

**Comment by unliar** [comment]
你是指回调接口拿到的阿里云传来的参数吗 那得你自己去把request body打印出来，回调接口没大注意这个问题，毕竟只要返回200就ok了。
```
// 打印下面的req.body
router.post("/ossCallback", (req, res, next) => {
  res.json({
    statusCode: 200,
    message: 'oss参数回调',
    result: {
      ...req.body
    }
  })
})
```

**Comment by zenghuabin** [comment]
我直接用你的例子，调用我的服务获取的token，也没去设置回调接口 然后直接就是  net::ERR_CONNECTION_RESET 报这个错，不知道啥原因，阿里云上也配置了跨域

**Comment by zenghuabin** [comment]
你微信发我可以么，我直接微信上找你快一点

**Comment by unliar** [comment]
> 你微信发我可以么，我直接微信上找你快一点

 

> 我直接用你的例子，调用我的服务获取的token，也没去设置回调接口 然后直接就是 net::ERR_CONNECTION_RESET 报这个错，不知道啥原因，阿里云上也配置了跨域

项目的回调接口是我之前公司的。。。。现在应该是不能用了，你把回调设置成你服务器的ip地址就ok了

**Comment by unliar** [comment]
> 你微信发我可以么，我直接微信上找你快一点

微信号是  lzt224
